default_controller:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: "/"

api_controllers:
    resource: "@AppBundle/Controller/Api/"
    type:     annotation
    prefix: "/api"

